@startuml
package "Algorithm" {
   !include firstchoicealgorithm.iuml
   !include solvingalgorithm.iuml
   !include randomalgorithm.iuml
   !include statistic.iuml
}
package "Errors" {
   !include wrongcsvformat.iuml
   !include notenoughplaces.iuml
}
!include importcsv.iuml
!include pupil.iuml
!include project.iuml
!include school.iuml
!include projecttyp.iuml
!include teacher.iuml

package "GUI" {
   !include mainwindow.iuml
   !include statisticview.iuml
   !include aboutview.iuml
   !include licenceview.iuml
}

FirstChoiceAlgorithm --|> SolvingAlgorithm
RandomAlgorithm --|> SolvingAlgorithm

Pupil --* School
Project --* School
Project o-- Teacher

SolvingAlgorithm *-- Statistic
SolvingAlgorithm -- NotEnoughPlaces : > uses

ImportCSV -- WrongCSVFormat : > uses

MainWindow *-- StatisticView
Project "1" *-- "1" Projecttyp

ImportCSV -- Pupil : > uses
ImportCSV -- Project : > uses

MainWindow -- ImportCSV

MainWindow -- School
ImportCSV -- School
MainWindow -- SolvingAlgorithm
MainWindow *-- LicenceView
MainWindow *-- AboutView
@enduml
